### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by vseledtsov** [swkrueger/signrider#1]
Thanks for the work you've done!
Where I can find train samples? Can you share it?

**Comment by swkrueger** [comment]
Thank you for your interest in SignRider. Our training set contains a few hundred samples of a subset of South Africa's road signs. We do not share the training data publicly, but will share it on request. I can send you a link to the training sets as well as a short report on SignRider if you provide me with your contact details for a private means of communication, such as an email address.

**Comment by vseledtsov** [comment]
You really help me out
thisburninglife@gmail.com

**Comment by swkrueger** [comment]
Check your inbox... :email: :smiley:
